#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
KEYSTORE_DIR="${HOME}/.foundry/keystores"
DEFAULT_ACCOUNT="pactpay-sepolia"
EXPECTED_CHAIN_ID="11155111"

PRIVATE_KEY=""
WALLET_OUTPUT=""
TEMP_ENV=""

cleanup() {
  PRIVATE_KEY=""
  WALLET_OUTPUT=""
  if [[ -n "$TEMP_ENV" && -f "$TEMP_ENV" ]]; then
    rm -f "$TEMP_ENV"
  fi
}
trap cleanup EXIT INT TERM

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

require_command cast
require_command sed
require_command grep

cd "$ROOT_DIR"
mkdir -p "$KEYSTORE_DIR"

# Preserve existing non-secret configuration when the script is rerun.
SEPOLIA_RPC_URL=""
DEPLOYER_ACCOUNT=""
DEPLOYER_ADDRESS=""
ETHERSCAN_API_KEY=""
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

printf '%s\n' 'PactPay Sepolia setup'
printf '%s\n' '----------------------'
printf '%s\n' 'This creates or reuses an encrypted Foundry keystore.'
printf '%s\n\n' 'The private key is never written to contracts/.env.'

if [[ -n "${SEPOLIA_RPC_URL:-}" ]]; then
  read -rsp 'Sepolia RPC URL (press Enter to keep the current value): ' RPC_INPUT
  printf '\n'
  RPC_URL="${RPC_INPUT:-$SEPOLIA_RPC_URL}"
else
  read -rsp 'Sepolia RPC URL: ' RPC_URL
  printf '\n'
fi

if [[ -z "$RPC_URL" ]]; then
  printf 'A Sepolia RPC URL is required.\n' >&2
  exit 1
fi

printf 'Checking RPC network...\n'
CHAIN_ID="$(cast chain-id --rpc-url "$RPC_URL")"
if [[ "$CHAIN_ID" != "$EXPECTED_CHAIN_ID" ]]; then
  printf 'Refusing setup: expected Sepolia chain ID %s, received %s.\n' \
    "$EXPECTED_CHAIN_ID" "$CHAIN_ID" >&2
  exit 1
fi

ACCOUNT_DEFAULT="${DEPLOYER_ACCOUNT:-$DEFAULT_ACCOUNT}"
read -rp "Foundry account name [$ACCOUNT_DEFAULT]: " ACCOUNT_INPUT
ACCOUNT_NAME="${ACCOUNT_INPUT:-$ACCOUNT_DEFAULT}"

if [[ ! "$ACCOUNT_NAME" =~ ^[A-Za-z0-9._-]+$ ]]; then
  printf 'Account names may contain only letters, numbers, dot, underscore and hyphen.\n' >&2
  exit 1
fi

KEYSTORE_FILE="$KEYSTORE_DIR/$ACCOUNT_NAME"
if [[ -f "$KEYSTORE_FILE" ]]; then
  read -rp "Account '$ACCOUNT_NAME' already exists. Reuse it? [y/N]: " REUSE
  case "$REUSE" in
    y|Y|yes|YES)
      ;;
    *)
      printf 'Setup cancelled. Rerun and choose a different account name.\n'
      exit 1
      ;;
  esac
else
  printf '\nGenerating a new deployer wallet...\n'
  WALLET_OUTPUT="$(cast wallet new)"
  DEPLOYER_ADDRESS="$(printf '%s\n' "$WALLET_OUTPUT" \
    | sed -nE 's/^[[:space:]]*Address:[[:space:]]*(0x[0-9A-Fa-f]{40}).*/\1/p' \
    | head -n 1)"
  PRIVATE_KEY="$(printf '%s\n' "$WALLET_OUTPUT" \
    | sed -nE 's/^[[:space:]]*Private key:[[:space:]]*(0x[0-9A-Fa-f]{64}).*/\1/p' \
    | head -n 1)"

  if [[ -z "$DEPLOYER_ADDRESS" || -z "$PRIVATE_KEY" ]]; then
    printf 'Unable to parse the generated wallet output. No keystore was written.\n' >&2
    exit 1
  fi

  printf 'Encrypting the wallet as Foundry account %s.\n' "$ACCOUNT_NAME"
  printf 'Create and confirm a strong keystore password when Cast prompts you.\n'
  cast wallet import "$ACCOUNT_NAME" --private-key "$PRIVATE_KEY"

  # Remove the raw key from the shell as soon as the encrypted import completes.
  PRIVATE_KEY=""
  WALLET_OUTPUT=""
fi

KEYSTORE_ADDRESS="$(cast wallet address --account "$ACCOUNT_NAME")"
if [[ -z "$KEYSTORE_ADDRESS" ]]; then
  printf 'Unable to resolve the address for Foundry account %s.\n' "$ACCOUNT_NAME" >&2
  exit 1
fi

if [[ -n "${DEPLOYER_ADDRESS:-}" && "${KEYSTORE_ADDRESS,,}" != "${DEPLOYER_ADDRESS,,}" ]]; then
  printf 'Keystore address mismatch: generated %s, imported %s.\n' \
    "$DEPLOYER_ADDRESS" "$KEYSTORE_ADDRESS" >&2
  exit 1
fi
DEPLOYER_ADDRESS="$KEYSTORE_ADDRESS"

umask 077
TEMP_ENV="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
{
  printf '# Generated by scripts/setup-sepolia.sh. Never commit this file.\n'
  printf 'SEPOLIA_RPC_URL=%q\n' "$RPC_URL"
  printf 'DEPLOYER_ACCOUNT=%q\n' "$ACCOUNT_NAME"
  printf 'DEPLOYER_ADDRESS=%q\n' "$DEPLOYER_ADDRESS"
  printf 'ETHERSCAN_API_KEY=%q\n' "${ETHERSCAN_API_KEY:-}"
} > "$TEMP_ENV"
mv "$TEMP_ENV" "$ENV_FILE"
TEMP_ENV=""
chmod 600 "$ENV_FILE"

BLOCK_NUMBER="$(cast block-number --rpc-url "$RPC_URL")"
BALANCE_WEI="$(cast balance "$DEPLOYER_ADDRESS" --rpc-url "$RPC_URL")"
BALANCE_ETH="$(cast to-unit "$BALANCE_WEI" ether)"

printf '\nSetup complete\n'
printf 'Network:  Sepolia (%s)\n' "$CHAIN_ID"
printf 'Block:    %s\n' "$BLOCK_NUMBER"
printf 'Account:  %s\n' "$ACCOUNT_NAME"
printf 'Address:  %s\n' "$DEPLOYER_ADDRESS"
printf 'Balance:  %s ETH (%s wei)\n' "$BALANCE_ETH" "$BALANCE_WEI"
printf 'Config:   %s\n' "$ENV_FILE"
printf 'Keystore: %s\n' "$KEYSTORE_FILE"
printf '\nRun: bash scripts/sepolia-status.sh\n'
